//thathsara

export const dummyDoctorNotes = [
  {
    id: 1,
    doctorName: "Dr. Kasun Perera",
    specialization: "General Physician",
    visitDate: "2025-01-15",
    visitTime: "10:30 AM",
    note: "Patient presented with mild fever and cough. Prescribed antibiotics and advised rest. Follow-up in 5 days if symptoms persist. Blood pressure normal at 120/80. Temperature: 99.5°F.",
    //diagnosis: "Upper Respiratory Infection",
  },
  {
    id: 2,
    doctorName: "Dr. Nimal Silva",
    specialization: "Cardiologist",
    visitDate: "2025-01-10",
    visitTime: "2:15 PM",
    note: "Regular cardiac check-up. ECG results normal. Patient's blood pressure slightly elevated at 135/85. Advised to reduce salt intake and increase physical activity. Continue current medication (Amlodipine 5mg daily). Schedule next appointment in 3 months.",
    //diagnosis: "Hypertension - Controlled",
  },
  {
    id: 3,
    doctorName: "Dr. Samanthi Fernando",
    specialization: "Endocrinologist",
    visitDate: "2025-01-05",
    visitTime: "11:00 AM",
    note: "Diabetes management review. HbA1c levels at 6.8% - well controlled. Fasting blood sugar: 110 mg/dL. Patient following diet plan effectively. Continue Metformin 500mg twice daily. Emphasized importance of regular exercise and monitoring blood sugar levels.",
    //diagnosis: "Type 2 Diabetes Mellitus",
  },
  {
    id: 4,
    doctorName: "Dr. Kasun Perera",
    specialization: "General Physician",
    visitDate: "2024-12-20",
    visitTime: "9:45 AM",
    note: "Annual health screening. All vital signs normal. Cholesterol levels within acceptable range. Patient maintaining healthy lifestyle. Recommended continuation of current diet and exercise routine. No medication changes needed.",
    //diagnosis: "Routine Check-up - Healthy",
  },
  {
    id: 5,
    doctorName: "Dr. Ruwan Jayawardena",
    specialization: "Dermatologist",
    visitDate: "2024-12-15",
    visitTime: "3:30 PM",
    note: "Patient complained of skin rash on arms. Diagnosed as contact dermatitis. Prescribed topical corticosteroid cream and antihistamine. Advised to avoid suspected allergen (certain fabric detergent). Follow-up in 2 weeks if no improvement.",
    //diagnosis: "Contact Dermatitis",
  },
  {
    id: 6,
    doctorName: "Dr. Nimali Wickramasinghe",
    specialization: "Ophthalmologist",
    visitDate: "2024-12-10",
    visitTime: "4:00 PM",
    note: "Eye examination completed. Vision test shows slight deterioration in left eye. Prescribed new glasses prescription. No signs of cataracts or glaucoma. Recommended annual eye check-ups. Current prescription: Right eye -1.50, Left eye -1.75.",
    //diagnosis: "Myopia - Mild",
  },
  {
    id: 7,
    doctorName: "Dr. Nimal Silva",
    specialization: "Cardiologist",
    visitDate: "2024-11-15",
    visitTime: "1:30 PM",
    note: "Follow-up for hypertension management. Blood pressure improved to 128/82. Patient compliance with medication is good. Lipid profile shows improvement - LDL cholesterol decreased to 110 mg/dL. Continue current treatment plan. Next visit in 3 months.",
    //diagnosis: "Hypertension - Improving",
  },
  {
    id: 8,
    doctorName: "Dr. Anura Dissanayake",
    specialization: "Orthopedic Surgeon",
    visitDate: "2024-11-05",
    visitTime: "10:00 AM",
    note: "Patient experiencing lower back pain. X-ray shows mild degenerative changes in lumbar spine. Prescribed pain medication and muscle relaxants. Recommended physical therapy sessions. Advised to avoid heavy lifting and maintain proper posture. Follow-up in 4 weeks.",
    //diagnosis: "Lumbar Spondylosis",
  },
];
